
---
apiVersion: v1
kind: Namespace
metadata:
  name: tabby

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tabby-data
  labels:
    app: tabby
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tabby
  name: tabby
  namespace: tabby
spec:
  containers:
  - args:
    - serve
    - --model
    - TabbyML/CodeLlama-7B
    - --device
    - cuda
    image: tabbyml/tabby
    imagePullPolicy: Always
    name: tabby
    resources:
      limits:
        nvidia.com/gpu: 1
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    ports:
    - containerPort: 8080
      name: tabbby-svc
    volumeMounts:
    - mountPath: "~/.tabby"
      name: tabby-data
  restartPolicy: Always
  volumes:
  - name: tabby-data
    persistentVolumeClaim:
      claimName: tabby-data

---
apiVersion: v1
kind: Service
metadata:
  name: tabby-svc
  labels:
    app: tabby
spec:
  clusterIP: None
  ports:
    - port: 8080
  selector:
    app: tabby

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: tabby
  namespace: tabby
  labels: {}
spec:
  to:
    kind: Service
    name: tabby-svc
  tls: null
  port:
    targetPort: http
